apiVersion: v1
kind: Service
metadata:
  name: elements-recorder-front-service
spec:
  type: NodePort
  selector:
    app: elements-recorder-front
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31111
